### ISSUE TITLE
Wrong mapping of constants?

### ISSUE THREAD

**Issue by Matthew-Dove** [Baloons-Pop-3/Baloons-Pop-Three#10]
[Here](https://github.com/Baloons-Pop-3/Baloons-Pop-Three/blob/master/Source/GameFacade.cs#L18) a field called ROWS, maps to a [parameter fieldCols](https://github.com/Baloons-Pop-3/Baloons-Pop-Three/blob/master/Source/Models/GameField.cs#L16).

It looks like the first two mappings are wrong, as rows is mapping to cols, and cols is mapping to rows.

**Comment by antoanelenkov** [comment]
Thanks, it is fixed now :)
