### ISSUE TITLE
Define Interfaces for the classed that don't have ones

### ISSUE THREAD

**Issue by antoanelenkov** [Baloons-Pop-3/Baloons-Pop-Three#9]
Define Interfaces and change the type of parameters in all constructor to be these interfaces instead of concrete classes(solving dependency inversion problem)

**Comment by Matthew-Dove** [comment]
Hey, I have done this for you, seems I don't have permission to make a pull request though?

**Comment by antoanelenkov** [comment]
Hello, Matthew. Thank you for your help, but this is educational project in which we are not allowed to let other people contributing in this repository. Anyways, your help is appreciated  and you have any other issues, feel free to write comments. :)

**Comment by Hris21** [comment]
Done.
